name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build package dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-none-eabi

      - name: Build dependencies
        run: |
          echo "Number of processors:" `nproc`
          make get-deps -j `nproc`

      - name: Build stm32_m3bms firmware
        run: |
          make

      - uses: actions/upload-artifact@v4
        with:
          name: stm32_m3bms firmware binary
          path: stm32_m3bms.bin

      - uses: actions/upload-artifact@v4
        with:
          name: stm32_m3bms firmware hex
          path: stm32_m3bms.hex
